spring:
  application:
    name: aws-rds-create

---
# create-rds profile
spring:
  profiles:
    active: create-rds

rds:
  dbName: myappdb
  instanceIdentifier: myapp-db-instance
  username: myappadmin
  password: SuperSecretPass123!
  secretName: myappdb-secret

---
# Default profile (when no profile is active)
spring:
  profiles:
    active: default
  main:
    web-application-type: none

# AWS configuration (common to all profiles)
aws:
  region: ap-south-1