name: Deploy RDS Instance

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        permissions:
          id-token: write
          contents: read

        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Setup JDK 17
            uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'temurin'

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v2
            with:
              role-to-assume: arn:aws:iam::339495302685:role/rds-create-from-code
              aws-region: ap-south-1

          - name: Build with Maven
            run: mvn clean install

          - name: Run App with create-rds profile
            run: java -jar target/aws-rds-create.jar --spring.profiles.active=create-rds